### ISSUE TITLE
configure threw following error

### ISSUE THREAD

**Issue by samundra** [foss-np/anubad#5]
### ./configure threw - 404 page not found error

I cloned the git repo and then used `./configure` which threw the following error

``` bash
samundra@samshrestha:~/Projects/anubad$ ./configure 
Downloading glossary
--2016-02-16 00:42:03--  https://github.com/foss-np/np-l10n-glossary/archive/current.tar.gz
Resolving github.com (github.com)... 192.30.252.130
Connecting to github.com (github.com)|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/foss-np/np-l10n-glossary/tar.gz/current [following]
--2016-02-16 00:42:04--  https://codeload.github.com/foss-np/np-l10n-glossary/tar.gz/current
Resolving codeload.github.com (codeload.github.com)... 192.30.252.162
Connecting to codeload.github.com (codeload.github.com)|192.30.252.162|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-16 00:42:06 ERROR 404: Not Found.

tar (child): current.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat ‘np-l10n-glossary-current’: No such file or directory

```

You can see the 404 Not Found error which basically means the pages were not found in the designated places. `configure` script tries to download `https://github.com/foss-np/np-l10n-glossary/archive/current.tar.gz`. This path is missing from the [np-l10n-glossary](https://github.com/foss-np/np-l10n-glossary) repo and is causing the above issue.

**Comment by rhoit** [comment]
oh! sorry there was no **current** tag in the np-l10n-glossary!
I guess its time to make the build test, 

hey @nootanghimire up for updating wiki what do you say!
you can write a section about fixing these kinda problem, and how to deal with manually.

Its fixed now, should work fine now,

**Comment by samundra** [comment]
Regarding the manual one, I can work on that part :) it's already in the readme. We just have to structure it nicely :)

**Comment by rhoit** [comment]
@samundra developer kinda get lazy when it comes to write documentation, we need the power users.

**Comment by samundra** [comment]
searching for power users :) Let's update wiki page.

**Comment by krazedkrish** [comment]
:+1:
